language: node_js
node_js:
- '6'

services:
- mongodb

cache:
  directories:
    - node_modules

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: DSchroederOSU/SeniorCapstone
  bucket: energy-dashboard
  region: us-west-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: energy-dashboard
  key: latest.zip
  bundle_type: zip
  application: OSUEnergyDashboard
  deployment_group: OSUEnergyDashboard
  region: us-west-2
  on: *2

script:
  - forever stopall
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
  - cd ~/apps/SeniorCapstone/Source/
  - forever start server.js
  - forever start dataServer.js
